version: '3'

services:
  mysqlserver:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: 'Password2021^^'
#-- Uncomment if you wish to persist volumes
#    volumes:
#      - ./database:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  appsrver:
    depends_on:
      - mysqlserver
    build:
      context: ./
      dockerfile: Docker/www/Dockerfile
    restart: unless-stopped
    ports:
      - 8888:80
      - 9000:9000
      - 9003:9003
    volumes:
      - ./www:/var/www/html
    environment:
      XDEBUG_CONFIG: 'remote_host=192.168.4.26'

  smtp4dev:
    depends_on:
      - mysqlserver
    image: rnwood/smtp4dev:v3
    restart: unless-stopped
    ports:
      - 5000:80
      - 5025:25
      - 5870:587
#-- Uncomment if you wish to persist volumes
#    volumes:
#      - ./smtp4dev:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev